export const en = {
  'analytics.title': 'Usage sharing',
  'analytics.explanation': 'Share which app features you use with a random ID to help improve the app.',
  'analytics.share': 'Share',
  'analytics.dontShare': "Don't share",
  'error.title': 'This screen couldn’t load',
  'error.message': 'Try again to reopen this screen.',
  'error.repeated': 'This screen still couldn’t load. Try again, or go to the start of the app.',
  'error.retry': 'Try again',
  'error.goToStart': 'Go to start',
  'onboarding.skip': 'Skip',
  'onboarding.next': 'Next',
  'onboarding.done': 'Get started',
  'onboarding.progress': 'Page {current} of {total}',
  'settings.title': 'Settings',
  'settings.theme': 'Theme',
  'settings.theme.system': 'System',
  'settings.theme.light': 'Light',
  'settings.theme.dark': 'Dark',
  'settings.language': 'Language',
  'settings.language.system': 'System',
  'settings.about': 'About',
  'settings.privacy': 'Privacy policy',
  'settings.contact': 'Contact',
  'settings.rate': 'Rate the app',
  'settings.version': 'Version',
  'settings.premium': 'Premium',
  'settings.premium.plans': 'See plans',
  'settings.premium.active': 'Premium is active',
} as const;
