export const en = {
  'analytics.title': 'Usage sharing',
  'analytics.explanation': 'Share which app features you use with a random ID to help improve the app.',
  'analytics.share': 'Share',
  'analytics.dontShare': "Don't share",
  'reminders.title': 'Daily reminder',
  'reminders.explanation': 'Allow notifications to receive this reminder each day at your chosen time.',
  'reminders.time': 'Time (24-hour format)',
  'reminders.timePlaceholder': '09:00',
  'reminders.enabled': 'Enable',
  'reminders.openSettings': 'Open settings',
  'reminders.invalidTime': 'Enter a time from 00:00 to 23:59.',
  'reminders.denied': 'Notifications are off. Allow them in your device settings to receive reminders.',
  'reminders.failed': 'The reminder could not be saved. Try again.',
  'error.title': 'This screen couldn’t load',
  'error.message': 'Try again to reopen this screen.',
  'error.repeated': 'This screen still couldn’t load. Try again, or go to the start of the app.',
  'error.retry': 'Try again',
  'error.goToStart': 'Go to start',
  'onboarding.skip': 'Skip',
  'onboarding.next': 'Next',
  'onboarding.done': 'Get started',
  'onboarding.progress': 'Page {current} of {total}',
  'settings.title': 'Settings',
  'settings.theme': 'Theme',
  'settings.theme.system': 'System',
  'settings.theme.light': 'Light',
  'settings.theme.dark': 'Dark',
  'settings.language': 'Language',
  'settings.language.system': 'System',
  'settings.about': 'About',
  'settings.privacy': 'Privacy policy',
  'settings.contact': 'Contact',
  'settings.rate': 'Rate the app',
  'settings.version': 'Version',
  'settings.premium': 'Premium',
  'settings.premium.plans': 'See plans',
  'settings.premium.active': 'Premium is active',
  'settings.premium.manage': 'Manage subscription',
} as const;
