export const en = {
  'onboarding.title': 'Onboarding',
  'onboarding.continue': 'Continue',
  'settings.title': 'Settings',
  'settings.theme': 'Theme',
  'settings.theme.system': 'System',
  'settings.theme.light': 'Light',
  'settings.theme.dark': 'Dark',
  'settings.language': 'Language',
  'settings.language.system': 'System',
  'settings.about': 'About',
  'settings.privacy': 'Privacy policy',
  'settings.contact': 'Contact',
  'settings.rate': 'Rate the app',
  'settings.restore': 'Restore purchases',
  'settings.version': 'Version',
} as const;
