export const en = {
  'tasks.empty': 'Your open tasks will appear here.',
  'tasks.add': 'Add task',
  'tasks.title': 'Task title',
  'tasks.save': 'Save task',
  'tasks.cancel': 'Cancel',
  'tasks.archive': 'Archive task',
  'tasks.archived': 'Task archived.',
  'tasks.undo': 'Undo',
  'tasks.previous': 'Previous task',
  'tasks.next': 'Next task',
  'tasks.current': 'Current task',
  'tasks.position': '{current} of {total}',
  'tasks.saveError': 'Could not save your change. Try again.',
  'feature.title': 'Tasks',
  'onboarding.1.title': 'Welcome',
  'onboarding.1.body': 'Keep your place when you switch tasks.',
  'onboarding.2.title': 'Leave a note',
  'onboarding.2.body': 'Save where you were and what comes next.',
  'onboarding.3.title': 'Pick up again',
  'onboarding.3.body': 'Return to a task when you are ready.',
  'paywall.title': 'Premium',
  'paywall.body': 'Placeholder for what premium adds. Each app writes its own line.',
} as const;
