export const en = {
  'tasks.empty': 'Your open tasks will appear here.',
  'tasks.add': 'Add task',
  'tasks.title': 'Task title',
  'tasks.save': 'Save task',
  'tasks.cancel': 'Cancel',
  'tasks.archive': 'Archive task',
  'tasks.archived': 'Task archived.',
  'tasks.undo': 'Undo',
  'tasks.previous': 'Previous task',
  'tasks.next': 'Next task',
  'tasks.current': 'Current task',
  'tasks.position': '{current} of {total}',
  'tasks.saveError': 'Could not save your change. Try again.',
  'leave.open': 'Leave',
  'leave.title': 'Leave a note',
  'leave.type': 'Type a note',
  'leave.placeholder': 'What were you doing, and what comes next?',
  'leave.save': 'Save note',
  'leave.retry': 'Retry',
  'leave.keepDraft': 'Keep draft',
  'leave.sorting': 'Sorting your note…',
  'leave.notSorted': 'Not sorted yet',
  'leave.sortFailed': 'Your note is saved; sorting failed. Retry now or later.',
  'leave.failedAudio': 'Voice note saved; transcription is not available yet.',
  'leave.permission': 'Allow microphone access to record a voice note.',
  'leave.recording': 'Recording',
  'leave.recordTap': 'Tap to start recording',
  'leave.recordDone': 'Finish recording',
  'leave.recordingFailed': 'Recording stopped. Your note is saved; try again or type it instead.',
  'feature.title': 'Tasks',
  'onboarding.1.title': 'Welcome',
  'onboarding.1.body': 'Keep your place when you switch tasks.',
  'onboarding.2.title': 'Leave a note',
  'onboarding.2.body': 'Save where you were and what comes next.',
  'onboarding.3.title': 'Pick up again',
  'onboarding.3.body': 'Return to a task when you are ready.',
  'paywall.title': 'Premium',
  'paywall.body': 'Placeholder for what premium adds. Each app writes its own line.',
} as const;
