import type { Translation } from '@factory/app';

import type { en } from './en.ts';

export const tr: Translation<typeof en> = {
  'tasks.empty': 'Açık görevleriniz burada görünecek.',
  'tasks.add': 'Görev ekle',
  'tasks.title': 'Görev başlığı',
  'tasks.save': 'Görevi kaydet',
  'tasks.cancel': 'İptal',
  'tasks.archive': 'Görevi arşivle',
  'tasks.archived': 'Görev arşivlendi.',
  'tasks.undo': 'Geri al',
  'tasks.previous': 'Önceki görev',
  'tasks.next': 'Sonraki görev',
  'tasks.current': 'Geçerli görev',
  'tasks.position': '{current} / {total}',
  'tasks.saveError': 'Değişikliğiniz kaydedilemedi. Tekrar deneyin.',
  'leave.open': 'Ayrıl',
  'leave.title': 'Bir not bırakın',
  'leave.type': 'Not yazın',
  'leave.placeholder': 'Ne yapıyordunuz ve sırada ne var?',
  'leave.save': 'Notu kaydet',
  'leave.retry': 'Tekrar dene',
  'leave.keepDraft': 'Taslağı sakla',
  'leave.sorting': 'Notunuz düzenleniyor…',
  'leave.notSorted': 'Henüz düzenlenmedi',
  'leave.sortFailed': 'Notunuz kaydedildi; düzenleme başarısız oldu. Şimdi veya daha sonra tekrar deneyin.',
  'leave.failedAudio': 'Sesli not kaydedildi; henüz yazıya dökülemedi.',
  'leave.permission': 'Sesli not kaydetmek için mikrofon izni verin.',
  'leave.recording': 'Kayıt yapılıyor',
  'leave.recordTap': 'Kaydı başlatmak için dokunun',
  'leave.recordDone': 'Kaydı bitir',
  'leave.recordingFailed': 'Kayıt durdu. Notunuz saklandı; tekrar deneyin veya yazın.',
  'feature.title': 'Görevler',
  'onboarding.1.title': 'Hoş geldiniz',
  'onboarding.1.body': 'Görev değiştirirken kaldığınız yeri koruyun.',
  'onboarding.2.title': 'Not bırakın',
  'onboarding.2.body': 'Not bırakın için yer tutucu.',
  'onboarding.3.title': 'Devam edin',
  'onboarding.3.body': 'Hazır olduğunuzda görevinize dönün.',
  'paywall.title': 'Premium',
  'paywall.body': 'Premium ile gelenler için yer tutucu. Her uygulama kendi metnini yazar.',
};
