export const en = {
  'disclosure.title': 'Send text to AI?',
  'disclosure.body': 'The text you enter will be sent to the configured AI provider. We do not store it on our server. When OpenRouter is configured, it may route your text to another model provider. OpenRouter says its prompt and response logging is off by default and can be enabled in account settings; it still stores request metadata. The selected provider has separate logging, retention, and training policies, which may differ. Please remove anything you do not have permission to share.',
  'disclosure.send': 'Send to AI',
  'disclosure.cancel': 'Cancel',
  'error.unavailable': 'AI is unavailable right now. Please try again later.',
  'error.unauthorized': 'Your AI session expired. Please try again.',
  'error.too_long': 'This text is too long. Shorten it and try again.',
  'error.invalid_request': 'Check the text and try again.',
  'error.daily_limit': 'You have used today’s AI requests. More are available at {time}.',
  'error.budget_limit': 'AI is unavailable for today. Please try again at {time}.',
  'error.burst_limit': 'Too many requests at once. Please wait a minute and try again.',
  'error.provider_error': 'The AI provider could not finish. Please try again.',
  'error.cancelled': 'The text was not sent.',
  'limit.premium': 'See Premium for more daily requests.',
} as const;
